CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "activo" boolean DEFAULT true,
  "rol_id" integer NOT NULL
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "description" text NOT NULL,
  "category_id" integer NOT NULL,
  "date" date NOT NULL,
  "priority_id" integer NOT NULL,
  "state_id" integer NOT NULL,
  "created_by" integer NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "ticket_requesters" (
  "ticket_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("ticket_id", "user_id")
);

CREATE TABLE "ticket_assignees" (
  "ticket_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("ticket_id", "user_id")
);

CREATE TABLE "ticket_areas" (
  "ticket_id" integer NOT NULL,
  "area_id" integer NOT NULL,
  PRIMARY KEY ("ticket_id", "area_id")
);

CREATE TABLE "states" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "state" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "priorities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "priority" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "areas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "area" varchar(100) NOT NULL
);

CREATE TABLE "user_area" (
  "user_id" integer NOT NULL,
  "area_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "area_id")
);

CREATE TABLE "ticket_replies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("state_id") REFERENCES "states" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("priority_id") REFERENCES "priorities" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_requesters" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_requesters" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_assignees" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_assignees" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_areas" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_areas" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_area" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_area" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_replies" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_replies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
